# ansible-playbook --ask-become-pass remove_apache.yml
---
- hosts: all
  become: true
  tasks:

  - name: remove apache and php packages on Debian
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes