# ansible-playbook site.yml
---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache CentOs
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache Debian and Ubuntu
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMNCSj7tec2/AsUqMAQDSb4EVZhNyXkBE9dFbxdrgxrm anisble"

- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache and php for Ubuntu & Debian servers
    tags: apache,apache2,ubuntu 
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: install apache and php for CentOS servers
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: change email address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin fiekbuurman@gmail.com
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd (CentOs)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html files for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: start httpd (CentOs)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
    
  - name: install mariadb package (CentOs)
    tags: centos,db,mariadb 
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Unbuntu or Debian)
    tags: db,mariadb,ubuntu,debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
