# ansible-playbook --ask-become-pass site.yml
---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates CentOs
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates Debian and Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache and php for Ubuntu & Debian servers
    tags: apache,apache2,ubuntu 
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: install apache and php for CentOS servers
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy default html files for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:
    
  - name: install mariadb package (CentOs)
    tags: centos,db,mariadb 
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOs"

  - name: install mariadb package (Unbuntu or Debian)
    tags: db,mariadb,ubuntu,debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
